# Generated by Django 3.1.7 on 2021-02-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ticket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ticketshop.ticket'),
        ),
    ]
