# Generated by Django 3.1.7 on 2021-02-19 19:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketshop', '0002_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='in Lari', max_digits=8, verbose_name='Price'),
        ),
    ]
